/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javagrpcpractice;

import io.grpc.Server;
import io.grpc.ServerBuilder;
import javagrpcpractice.server.GreetServiceImpl;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws IOException, InterruptedException {
        System.out.println(new App().getGreeting());
        Server server = ServerBuilder.forPort(50051)
                .addService(new GreetServiceImpl())
                .build();

        server.start();

        //handle properly the shutdown
        Runtime.getRuntime().addShutdownHook(new Thread(()->{
            System.out.println("receive shutdown request");
            server.shutdown();
            System.out.println("Successfully stopped the server");
        }));

        //for grpc to be blocking for the main thread
        server.awaitTermination();
    }
}
